/**
 * CampusIQ centralized, context-aware download service.
 *
 * All Download / Borrow / Return / Receipt / Export / Payslip buttons
 * flow through this module. Each helper derives a contextual filename
 * (e.g. "Alex_Chen_Receipt_INV-2025-0017A.pdf") and renders a minimal
 * but genuinely-valid PDF on the fly.
 */

function buildPdfBytes(title: string, lines: string[]): Uint8Array {
  const encoder = new TextEncoder();
  const sanitize = (s: string) => s.replace(/[\r\n\t]/g, ' ').replace(/[()\\]/g, (ch) => '\\' + ch);

  const headerY = 780;
  const lineHeight = 22;
  const contentLines: string[] = [];
  contentLines.push('BT', '/F1 20 Tf', `72 ${headerY} Td`, `(${sanitize(title)}) Tj`, 'ET');

  contentLines.push('BT', '/F1 11 Tf');
  let y = headerY - 40;
  lines.forEach((l) => {
    contentLines.push(`72 ${y} Td`, `(${sanitize(l)}) Tj`, '0 0 Td');
    y -= lineHeight;
  });
  contentLines.push('ET');

  contentLines.push('BT', '/F1 9 Tf', `72 60 Td`, `(Generated by CampusIQ \\267 ${new Date().toISOString().slice(0, 19).replace('T', ' ')} UTC) Tj`, 'ET');

  const stream = contentLines.join('\n');
  const streamBytes = encoder.encode(stream);

  const objects: string[] = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
    `<< /Length ${streamBytes.length} >>\nstream\n${stream}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];

  let out = '%PDF-1.4\n%\xff\xff\xff\xff\n';
  const offsets: number[] = [];
  const chunks: Uint8Array[] = [];
  chunks.push(encoder.encode(out));
  let cursor = chunks[0].length;

  objects.forEach((body, i) => {
    offsets.push(cursor);
    const b = encoder.encode(`${i + 1} 0 obj\n${body}\nendobj\n`);
    chunks.push(b);
    cursor += b.length;
  });

  const xrefOffset = cursor;
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((o) => { xref += `${String(o).padStart(10, '0')} 00000 n \n`; });
  xref += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  chunks.push(encoder.encode(xref));

  const total = chunks.reduce((a, b) => a + b.length, 0);
  const merged = new Uint8Array(total);
  let off = 0;
  chunks.forEach((c) => { merged.set(c, off); off += c.length; });
  return merged;
}

export interface DownloadOptions {
  filename: string;
  title: string;
  lines: string[];
}

export function slugifyFilename(name: string): string {
  return (name || 'Document')
    .replace(/[^a-zA-Z0-9_\-. ]+/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .slice(0, 100) || 'Document';
}

/** Core: render+download a dummy PDF. */
export async function downloadDummyPdf({ filename, title, lines }: DownloadOptions): Promise<void> {
  const bytes = buildPdfBytes(title, lines);
  const blob = new Blob([new Uint8Array(bytes)], { type: 'application/pdf' });
  const base = slugifyFilename(filename);
  const finalName = base.toLowerCase().endsWith('.pdf') ? base : base + '.pdf';
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = finalName;
  a.rel = 'noopener';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

/* ==================== Contextual helpers ==================== */

export function downloadReceipt(args: { studentName: string; invoiceNo: string; description: string; amount: number; paidOn?: string | null; status: string }) {
  const nameSlug = slugifyFilename(args.studentName);
  return downloadDummyPdf({
    filename: `${nameSlug}_Receipt_${args.invoiceNo}`,
    title: 'CampusIQ \u00b7 Fee Receipt',
    lines: [
      `Student: ${args.studentName}`,
      `Invoice: ${args.invoiceNo}`,
      `Description: ${args.description}`,
      `Amount: Rs ${args.amount.toLocaleString()}`,
      `Status: ${args.status}`,
      args.paidOn ? `Paid On: ${args.paidOn}` : `Paid On: --`,
      '',
      'Thank you for your payment. Keep this receipt for your records.',
      'For queries, write to accounts@campusiq.edu.',
    ],
  });
}

export function downloadBookCopy(args: { title: string; author: string; isbn: string; action: 'borrow' | 'reserve' | 'return' }) {
  const verb = args.action === 'borrow' ? 'Borrow Slip' : args.action === 'reserve' ? 'Reservation Slip' : 'Return Slip';
  return downloadDummyPdf({
    filename: `${args.title}_${verb.replace(' ', '_')}`,
    title: `CampusIQ Library \u00b7 ${verb}`,
    lines: [
      `Title: ${args.title}`,
      `Author: ${args.author}`,
      `ISBN: ${args.isbn}`,
      `Action: ${verb}`,
      `Issued on: ${new Date().toLocaleDateString()}`,
      `Due in: 14 days`,
      '',
      'Please handle library material with care. Damaged or lost copies',
      'will incur a replacement fee as per the institute policy.',
    ],
  });
}

export function downloadDocument(args: { title: string; category: string; ownerName: string }) {
  return downloadDummyPdf({
    filename: args.title,
    title: `CampusIQ \u00b7 ${args.title}`,
    lines: [
      `Document: ${args.title}`,
      `Category: ${args.category}`,
      `Owner: ${args.ownerName}`,
      `Downloaded: ${new Date().toLocaleString()}`,
      '',
      'This is an officially generated document from CampusIQ.',
      'It is provided for demonstration and placeholder purposes.',
    ],
  });
}

export function downloadPayslip(args: { employeeName: string; employeeId: string; designation: string; payPeriod: string; basic: number; allowances: number; deductions: number; netPay: number; status: string }) {
  const slug = slugifyFilename(args.employeeName);
  return downloadDummyPdf({
    filename: `${slug}_Payslip_${args.payPeriod}`,
    title: `CampusIQ \u00b7 Payslip \u00b7 ${args.payPeriod}`,
    lines: [
      `Employee: ${args.employeeName}`,
      `Employee ID: ${args.employeeId}`,
      `Designation: ${args.designation}`,
      `Pay period: ${args.payPeriod}`,
      '',
      `Basic: Rs ${args.basic.toLocaleString()}`,
      `Allowances: Rs ${args.allowances.toLocaleString()}`,
      `Deductions: Rs ${args.deductions.toLocaleString()}`,
      `Net pay: Rs ${args.netPay.toLocaleString()}`,
      `Status: ${args.status}`,
    ],
  });
}

export function downloadGeneric(filename: string, title: string, lines: string[] = []) {
  return downloadDummyPdf({ filename, title, lines: lines.length ? lines : ['Auto-generated document from CampusIQ.'] });
}
